# Generated by Django 5.1.7 on 2025-03-23 12:10

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(help_text='Enter the name of the event', max_length=255)),
                ('description', models.TextField(help_text='Enter a description of the event')),
                ('year', models.IntegerField(help_text='Enter the year (YYYY)')),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image related to the event', max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Honour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honours', to=settings.AUTH_USER_MODEL)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honours', to='timeline.timeline')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('timeline', 'user'), name='unique_timeline_user')],
            },
        ),
    ]
